AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Checks the status of Kindle publication and sends emails

Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: content-api
  App:
    Description: Application name
    Type: String
    Default: kindle-publication-check
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
  DeployBucket:
    Description: Bucket to copy files to
    Type: String
    Default: content-api-dist
  ManifestURL:
    Description: URL of the latest manifest file (should redirect)
    Type: String
  KindleBucket:
    Description: S3 bucket with the generated kindle files
    Type: String
  SourceAddress:
    Description: Source email address
    Type: String
  PassTargetAddresses:
    Description: Target email addresses to use when tests pass
    Type: String
  FailureTargetAddresses:
    Description: Target email addresses to use when tests fail
    Type: String
  MinimumArticleCount:
    Description: Minimum expected articles in an edition
    Type: Number
Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${App}-${Stage}
      Description: Checks the status of Kindle publication and sends emails
      Runtime: nodejs8.10
      Handler: lambda.handler
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          ManifestURL: !Ref ManifestURL
          KindleBucket: !Ref KindleBucket
          Stage: !Ref Stage
          SourceAddress: !Ref SourceAddress
          PassTargetAddresses: !Ref PassTargetAddresses
          FailureTargetAddresses: !Ref FailureTargetAddresses
          MinimumArticleCount: !Ref MinimumArticleCount
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/${App}/${App}.zip
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3::*:${KindleBucket}"
        - Statement:
            Effect: Allow
            Action:
              - ses:SendEmail
            Resource:
              - "*"
            Condition:
              StringEquals:
                ses:FromAddress: !Ref SourceAddress
