# Initiate a github actions-initiated build
name: Build and upload artifact on push to any branch
on:
  push: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      issues: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      # lifted from https://github.com/marketplace/actions/setup-yarn
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: '16.x'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          role-session-name: kindle-publication-check-build
      # Seed the build number with last number from TeamCity.
      - name: Update GITHUB_RUN_NUMBER
        run: |
          LAST_TEAMCITY_BUILD=59
          echo GITHUB_RUN_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD )) >> $GITHUB_ENV
      - run: yarn install
      - run: yarn run clean  # <-- delete any previous ./target dir
      - run: yarn run build  # <-- outputs files to ./target
      - run: cp package.json target # <-- without this we won't get our dependencies
      - run: cd target
      - run: yarn install --production  # <-- creates our node_modules etc for including in the .zip
      - run: cd ..
      - run: mkdir dist
      - run: zip -r dist/kindle-publication-check.zip target
      - uses: guardian/actions-riff-raff@v2
        with:
          app: kindle-publication-check
          configPath: riff-raff.yaml
          buildNumber: ${{ env.GITHUB_RUN_NUMBER }}
          contentDirectories: |
            kindle-publication-check:
              - dist/kindle-publication-check.zip
