# Initiate a github actions-initiated build
name: Build and upload artifact on push to any branch
on:
  push: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      issues: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      # Seed the build number with last number from TeamCity.
      - name: Update GITHUB_RUN_NUMBER
        run: |
          LAST_TEAMCITY_BUILD=59
          echo GITHUB_RUN_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD )) >> $GITHUB_ENV
      - name: Make sure we have yarn available
        # lifted from https://github.com/marketplace/actions/setup-yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: '16.x'
      - name: Install everything we need for the project
        run: yarn install
      - name: Clean and build to target dir
        run: |
          yarn run clean  # <-- delete any previous ./target dir
          yarn run build  # <-- outputs files to ./target
      -name: Copy package.json to target dir
        run: cp package.json target # <-- without this we won't get our dependencies
      -name: Go to target dir and install everything there
        run: |
          cd target
          yarn install --production  # <-- creates our node_modules etc for including in the .zip
      -name: See what we have at this point
        run: ls -al
      -name: Head back up a dir
        run: cd ..
      -name: Make a dist dir and create a .zip file in there
        run: |
          mkdir dist
          zip -r dist/kindle-publication-check.zip target
      - name: Acquire RiffRaff role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          role-session-name: kindle-publication-check-build
      - name: Send the .zip and riff-raff.yaml files to S3
        uses: guardian/actions-riff-raff@v2
        with:
          app: kindle-publication-check
          configPath: riff-raff.yaml
          buildNumber: ${{ env.GITHUB_RUN_NUMBER }}
          contentDirectories: |
            kindle-publication-check:
              - dist/kindle-publication-check.zip
