# Initiate a github actions-initiated build
name: Build and upload artifact on push to any branch
on:
  push: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      issues: read
      pull-requests: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Prepare Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    # Seed the build number with last number from TeamCity.
    - name: Update GITHUB_RUN_NUMBER
      run: |
        LAST_TEAMCITY_BUILD=59
        echo GITHUB_RUN_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD )) >> $GITHUB_ENV
    # now following example at https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs#example-using-yarn
    - name: Install dependencies with yarn
      run: yarn
    - name: Clean and build to target dir
      run: |
        yarn run clean
        yarn run build
    - name: Copy package.json to target dir
      run: cp package.json target
    - name: Go to target dir and install everything there
      run: |
        cd target
        yarn --production
    - name: See what we have at this point
      run: ls -al
    - name: Head back up a dir
      run: cd ..
    - name: Make a dist dir and create a .zip file in there
      run: |
        mkdir dist
        zip -r dist/kindle-publication-check.zip target
    - name: Acquire RiffRaff role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-1
        role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
        role-session-name: kindle-publication-check-build
    - name: Send the .zip and riff-raff.yaml files to S3
      uses: guardian/actions-riff-raff@v2
      with:
        app: kindle-publication-check
        configPath: riff-raff.yaml
        buildNumber: ${{ env.GITHUB_RUN_NUMBER }}
        contentDirectories: |
          kindle-publication-check:
            - dist/kindle-publication-check.zip
